//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReceiptManagement.Common.Helpers.Exceptions
{
    /// <summary>
    ///	The exception thrown when an error occurs while calling existance of an entity check based on where clause.
    /// </summary>
    [System.Serializable]
    public sealed class ExistsException : System.Exception
    {
    	#region Constructors & Factories
    
        //	Internal constructors since they shouldn't be called outside of the API.
        internal ExistsException() { }
    	internal ExistsException(System.Exception innerException) : base(innerException.Message, innerException) { }
        internal ExistsException(System.String message):base(message) { }
    		
    	/// <summary>
    	///		The factory used to a new ExistsException with inner exception.
    	/// </summary>
        public static Helpers.Exceptions.ExistsException Factory(System.Exception innerException)
    	{		
            return new Helpers.Exceptions.ExistsException(innerException);
        }
    	
    	/// <summary>
    	///		The factory used to a new ExistsException with a message.
    	/// </summary>
        public static Helpers.Exceptions.ExistsException Factory(System.String message)
    	{
            return new Helpers.Exceptions.ExistsException(message);
        }
    		
    	#endregion
    }
}
